In [6]:
import csv

with open("winequality-red.csv", "r") as f:
    wines = list(csv.reader(f, delimiter = ";"))
    print (wines[0:3])
    

[['xed acidity"', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [7]:
quality = [float(item[-1]) for item in wines[1:]]
#qualities = []
#for item in wines[1:]:
    #quality = float(item[-1])
    #qualities.append(quality)
    
print(quality[0:20])
print ('Average: ', sum(quality) / len(quality))

[5.0, 5.0, 5.0, 6.0, 5.0, 5.0, 5.0, 7.0, 7.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 7.0, 5.0, 4.0, 6.0]
Average:  5.6360225140712945


In [8]:
import numpy as np

arr1 = np.array(wines[1:], dtype=np.float)
print(arr1.shape)
print(arr1[-1])

(1599, 12)
[  6.        0.31      0.47      3.6       0.067    18.       42.        0.99549
   3.39      0.66     11.        6.     ]


In [9]:
np.zeros((2, 5))
np.random.rand(2,5)

array([[ 0.13212834,  0.07575496,  0.88499127,  0.87859486,  0.9276338 ],
       [ 0.55960456,  0.47183267,  0.47194043,  0.13201567,  0.06312704]])

In [10]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

# entire column slicing(column no.3)
print(wines[:,3])


[ 1.9  2.6  2.3 ...,  2.3  2.   3.6]


In [12]:
third_wine = wines[3,:]

sample = wines[0:5]
print (sample)

# slicing example~  sample[line range, element range]
# every line, last element
print (sample[:, -1])
# line number 2, element 0~2
print (sample[2, 0:3])
# line number 0~4(5), element 0~4(5)
print (sample[:5, 0:5])

[[  7.40000000e+00   7.00000000e-01   0.00000000e+00   1.90000000e+00
    7.60000000e-02   1.10000000e+01   3.40000000e+01   9.97800000e-01
    3.51000000e+00   5.60000000e-01   9.40000000e+00   5.00000000e+00]
 [  7.80000000e+00   8.80000000e-01   0.00000000e+00   2.60000000e+00
    9.80000000e-02   2.50000000e+01   6.70000000e+01   9.96800000e-01
    3.20000000e+00   6.80000000e-01   9.80000000e+00   5.00000000e+00]
 [  7.80000000e+00   7.60000000e-01   4.00000000e-02   2.30000000e+00
    9.20000000e-02   1.50000000e+01   5.40000000e+01   9.97000000e-01
    3.26000000e+00   6.50000000e-01   9.80000000e+00   5.00000000e+00]
 [  1.12000000e+01   2.80000000e-01   5.60000000e-01   1.90000000e+00
    7.50000000e-02   1.70000000e+01   6.00000000e+01   9.98000000e-01
    3.16000000e+00   5.80000000e-01   9.80000000e+00   6.00000000e+00]
 [  7.40000000e+00   7.00000000e-01   0.00000000e+00   1.90000000e+00
    7.60000000e-02   1.10000000e+01   3.40000000e+01   9.97800000e-01
    3.51000000e+

In [13]:
print (sample.dtype)
print (type(sample))

convert = sample.astype(np.int32)
print (convert.dtype)
print (convert)

float64
<class 'numpy.ndarray'>
int32
[[ 7  0  0  1  0 11 34  0  3  0  9  5]
 [ 7  0  0  2  0 25 67  0  3  0  9  5]
 [ 7  0  0  2  0 15 54  0  3  0  9  5]
 [11  0  0  1  0 17 60  0  3  0  9  6]
 [ 7  0  0  1  0 11 34  0  3  0  9  5]]


In [15]:
# one dimension array(vector)
rand_arr1 = np.random.rand(12)
# two dimension array(matrix)
rand_arr2 = np.random.rand(1, 12)

print (rand_arr1)
print (rand_arr1.shape)

[ 0.81099299  0.60869917  0.8560396   0.60386662  0.28687351  0.06569197
  0.93328178  0.35322255  0.751853    0.31948101  0.39300506  0.38656251]
(12,)


In [16]:
print (wines)
# sum of each columns
print (wines.sum(axis=0).shape)
# sum of each rows
print (wines.sum(axis=1).shape)

[[  7.4     0.7     0.    ...,   0.56    9.4     5.   ]
 [  7.8     0.88    0.    ...,   0.68    9.8     5.   ]
 [  7.8     0.76    0.04  ...,   0.65    9.8     5.   ]
 ..., 
 [  6.3     0.51    0.13  ...,   0.75   11.      6.   ]
 [  5.9     0.645   0.12  ...,   0.71   10.2     5.   ]
 [  6.      0.31    0.47  ...,   0.66   11.      6.   ]]
(12,)
(1599,)


In [17]:
# vector of bool type  
top_quality_wine = (wines[:, 10] > 12) & (wines[:, 11] > 7)
print (top_quality_wine.shape)
print (wines[top_quality_wine, 10:])

(1599,)
[[ 12.8   8. ]
 [ 12.6   8. ]
 [ 12.9   8. ]
 [ 13.4   8. ]
 [ 14.    8. ]
 [ 12.7   8. ]
 [ 12.5   8. ]
 [ 13.1   8. ]
 [ 14.    8. ]]


In [18]:
np.transpose(wines).shape

(12, 1599)

In [19]:
np.ravel(wines)

array([  7.4 ,   0.7 ,   0.  , ...,   0.66,  11.  ,   6.  ])

In [20]:
row_one = wines[1, :]
#print (row_one.reshape((2,6)))
print (np.reshape(row_one, (2,6)))
print (np.reshape(row_one, (3,4)))

# not changed
print (row_one)

[[  7.8      0.88     0.       2.6      0.098   25.    ]
 [ 67.       0.9968   3.2      0.68     9.8      5.    ]]
[[  7.8      0.88     0.       2.6   ]
 [  0.098   25.      67.       0.9968]
 [  3.2      0.68     9.8      5.    ]]
[  7.8      0.88     0.       2.6      0.098   25.      67.       0.9968
   3.2      0.68     9.8      5.    ]


In [24]:
white_wines = np.genfromtxt("winequality-white.csv", delimiter=";", skip_header=1)
print (white_wines.shape)

(4898, 12)


In [35]:
# vertical stack (should be same number of elements)
vres = np.vstack((wines, white_wines))
# vres = np.concatenate((wines, white_wines), axis=0)
print (vres.shape)
print (vres)

# dump array
dumparr = np.zeros((4898, 12))

# horizontal stack (should be same number of lines)
# concatenate function is generally used.
hres = np.concatenate((dumparr, white_wines), axis=1)
print (hres.shape)
print (hres)


(6497, 12)
[[  7.4    0.7    0.   ...,   0.56   9.4    5.  ]
 [  7.8    0.88   0.   ...,   0.68   9.8    5.  ]
 [  7.8    0.76   0.04 ...,   0.65   9.8    5.  ]
 ..., 
 [  6.5    0.24   0.19 ...,   0.46   9.4    6.  ]
 [  5.5    0.29   0.3  ...,   0.38  12.8    7.  ]
 [  6.     0.21   0.38 ...,   0.32  11.8    6.  ]]
(4898, 24)
[[  0.     0.     0.   ...,   0.45   8.8    6.  ]
 [  0.     0.     0.   ...,   0.49   9.5    6.  ]
 [  0.     0.     0.   ...,   0.44  10.1    6.  ]
 ..., 
 [  0.     0.     0.   ...,   0.46   9.4    6.  ]
 [  0.     0.     0.   ...,   0.38  12.8    7.  ]
 [  0.     0.     0.   ...,   0.32  11.8    6.  ]]


In [31]:
print (wines.shape)
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
# [0, 1, 2, 3]
b = np.arange(4)

print (b)
print (a[b, [0, 2, 0, 1]])

(1599, 12)
[0 1 2 3]
[ 1  6  7 11]


In [34]:
# transpose
c = np.array([[1,2], [3,4]])
print (c.T)
print (np.transpose(c))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
